import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

export { dayjs };

export const fmtDateTime = (d) => (d ? dayjs(d).format('DD MMM YYYY HH:mm') : '—');
export const fmtDate = (d) => (d ? dayjs(d).format('DD MMM YYYY') : '—');
export const fmtRelative = (d) => (d ? dayjs(d).fromNow() : '');
export const fmtNum = (n, digits) => (n == null || Number.isNaN(Number(n))
  ? '—'
  : Number(n).toLocaleString(undefined, digits != null ? { maximumFractionDigits: digits, minimumFractionDigits: digits } : undefined));
export const fmtPct = (v01) => (v01 == null ? '—' : `${Math.round(Number(v01) * 100)}%`);
export const humanize = (s) => String(s ?? '').replace(/_/g, ' ');

/**
 * The ten PS 26013 source types. `group` drives grouping in the UI, `geom` is what the worker
 * produces (rasters are stored as their footprint), `formats` mirrors the worker adapters.
 */
export const SOURCE_META = {
  drone_imagery:      { label: 'Drone imagery',        group: 'Imagery',   geom: 'footprint', color: '#8e44ad', formats: '.tif' },
  ori:                { label: 'Orthorectified (ORI)', group: 'Imagery',   geom: 'footprint', color: '#6c5ce7', formats: '.tif' },
  dsm_dtm:            { label: 'DSM / DTM',            group: 'Imagery',   geom: 'footprint', color: '#a29bfe', formats: '.tif' },
  cadastral:          { label: 'Cadastral maps',       group: 'Cadastre',  geom: 'polygon',   color: '#0d6efd', formats: '.geojson, .shp' },
  revenue:            { label: 'Revenue records',      group: 'Records',   geom: 'point',     color: '#d35400', formats: '.csv, .pdf (scanned → OCR)' },
  municipal_gis:      { label: 'Municipal GIS',        group: 'Cadastre',  geom: 'polygon',   color: '#16a085', formats: '.geojson, .shp' },
  utility:            { label: 'Utility networks',     group: 'Networks',  geom: 'line',      color: '#e84393', formats: '.geojson, .shp' },
  ground_truth:       { label: 'Ground truthing (GT)', group: 'Survey',    geom: 'point',     color: '#e67e22', formats: '.gpx, .csv' },
  gnss_cors:          { label: 'GNSS / CORS survey',   group: 'Survey',    geom: 'point',     color: '#c0392b', formats: '.csv (lon, lat, …)' },
  building_footprint: { label: 'Building footprints',  group: 'Cadastre',  geom: 'polygon',   color: '#f39c12', formats: '.geojson, .shp' },
  ai_extracted:       { label: 'AI-extracted features', group: 'GeoAI',    geom: 'polygon',   color: '#e8590c', formats: 'generated by feature extraction' },
};
/** The ten source types an officer uploads (AI-extracted layers are produced by the platform). */
export const UPLOAD_TYPES = Object.keys(SOURCE_META).filter((t) => t !== 'ai_extracted');
export const SOURCE_TYPES = Object.keys(SOURCE_META);
export const RASTER_TYPES = ['drone_imagery', 'ori', 'dsm_dtm'];
export const POLYGON_TYPES = ['cadastral', 'municipal_gis', 'building_footprint', 'ai_extracted'];
export const sourceLabel = (t) => SOURCE_META[t]?.label ?? humanize(t);
export const sourceColor = (t) => SOURCE_META[t]?.color ?? '#6c757d';

/** Mirrors worker/src/harmonize/match.py — used to explain confidence scores. */
export const SOURCE_RELIABILITY = {
  gnss_cors: 1.0, cadastral: 0.95, ground_truth: 0.9, building_footprint: 0.8,
  municipal_gis: 0.8, utility: 0.75, ai_extracted: 0.7, ori: 0.7, dsm_dtm: 0.7, revenue: 0.65, drone_imagery: 0.6,
};
export const CONFIDENCE_WEIGHTS = {
  geometric_match_score: { label: 'Geometric match', weight: 0.4 },
  attribute_match_score: { label: 'Attribute agreement', weight: 0.3 },
  source_reliability_weight: { label: 'Source reliability', weight: 0.2 },
  recency_score: { label: 'Recency', weight: 0.1 },
};

export const SOURCE_STATUS = {
  ready: 'success', processing: 'info', pending_ocr: 'warning', needs_georef: 'purple', failed: 'danger',
};

export const JOB_STATUS = { queued: 'secondary', running: 'info', done: 'success', failed: 'danger' };

export const JOB_LABEL = {
  NORMALIZE_SOURCE: 'Ingest & normalise', DIGITIZE_SOURCE: 'OCR digitisation', SCHEMA_MAP: 'Attribute mapping',
  HARMONIZE_WARD: 'Spatial matching', DETECT_CONFLICTS: 'Conflict detection', ASSEMBLE_WARD: 'Golden-record assembly',
  EXPORT_HARMONIZED: 'GeoPackage export', EXTRACT_FEATURES: 'AI feature extraction', FIX_TOPOLOGY: 'Topology correction',
  GEOREFERENCE: 'Geo-referencing', DETECT_CHANGES: 'Change detection', VALIDATE_WARD: 'Validation & sync',
};

export const EXTRACTION_METHODS = {
  auto: { label: 'Auto', hint: 'nDSM for elevation rasters, the ONNX model when configured, otherwise classical vision' },
  ndsm: { label: 'nDSM (height)', hint: 'DSM − DTM above a height threshold; DTM estimated by morphological filtering when not supplied' },
  model: { label: 'Deep-learning model', hint: 'ONNX building-segmentation model (FOOTPRINT_MODEL_PATH) run tile-by-tile' },
  classical: { label: 'Classical vision', hint: 'Vegetation/shadow-suppressed roof segmentation on RGB imagery' },
};

export const TOPOLOGY_TYPES = {
  overlap:           { label: 'Overlap',           color: '#dc3545', tone: 'danger',    fix: 'Clip the overlap out of the smaller parcel' },
  gap:               { label: 'Gap',               color: '#fd7e14', tone: 'orange',    fix: 'Merge the unclaimed strip into the neighbour with the longest shared edge' },
  sliver:            { label: 'Sliver',            color: '#ffc107', tone: 'warning',   fix: 'Absorb the hairline sliver into the adjacent parcel' },
  duplicate_vertex:  { label: 'Duplicate vertex',  color: '#6f42c1', tone: 'purple',    fix: 'Remove repeated / coincident vertices' },
  self_intersection: { label: 'Self-intersection', color: '#0dcaf0', tone: 'info',      fix: 'Repaired with make_valid during ingestion' },
};
export const TOPOLOGY_STATUS = { open: 'warning', auto_fixed: 'success', accepted: 'success', ignored: 'secondary' };

export const CHANGE_TYPES = {
  new_structure:      { label: 'New structure',      color: '#dc3545', tone: 'danger' },
  extension:          { label: 'Extension',          color: '#fd7e14', tone: 'orange' },
  vertical_extension: { label: 'Vertical extension', color: '#6f42c1', tone: 'purple' },
  reduction:          { label: 'Reduction',          color: '#0dcaf0', tone: 'info' },
  demolished:         { label: 'Demolished',         color: '#6c757d', tone: 'secondary' },
};
export const CHANGE_STATUS = { pending: 'secondary', confirmed: 'success', false_positive: 'danger' };

export const FINDING_TYPES = {
  unregistered_structure: { label: 'Unregistered structure', color: '#dc3545', tone: 'danger', hint: 'Structure on the ground with no cadastral parcel' },
  encroachment:           { label: 'Encroachment',           color: '#fd7e14', tone: 'orange', hint: 'Structure extends beyond its parcel boundary' },
  vacant_parcel:          { label: 'Vacant parcel',          color: '#0dcaf0', tone: 'info',   hint: 'Parcel with no detected structure' },
  attribute_drift:        { label: 'Attribute drift',        color: '#6f42c1', tone: 'purple', hint: 'Departments disagree on the parcel attributes' },
};

export const READINESS = {
  ready:            { label: 'Ready to finalise',   color: '#198754', tone: 'success' },
  blocked_conflict: { label: 'Blocked by conflict', color: '#dc3545', tone: 'danger' },
  blocked_topology: { label: 'Blocked by topology', color: '#fd7e14', tone: 'orange' },
  low_confidence:   { label: 'Low confidence',      color: '#ffc107', tone: 'warning' },
};

export const BAND = {
  auto_accept: { tone: 'success', label: 'Auto-accept' },
  review: { tone: 'warning', label: 'Review' },
  conflict: { tone: 'danger', label: 'Conflict' },
};

export const SEVERITY = {
  critical: { tone: 'danger', rank: 0 },
  high: { tone: 'orange', rank: 1 },
  medium: { tone: 'warning', rank: 2 },
  low: { tone: 'info', rank: 3 },
};

export const CONFLICT_STATUS = {
  pending: 'secondary', needs_review: 'warning', resolved: 'success', rejected: 'dark',
};

export const PROPERTY_STATUS = {
  pending:          { tone: 'secondary', label: 'Pending' },
  verified:         { tone: 'success',   label: 'Verified' },
  underassessed:    { tone: 'warning',   label: 'Underassessed' },
  false_positive:   { tone: 'danger',    label: 'False positive' },
  already_assessed: { tone: 'info',      label: 'Already assessed' },
};

export const DETECTION_TYPE = {
  new_build:     { tone: 'danger', label: 'New build' },
  change_of_use: { tone: 'orange', label: 'Change of use' },
};

export const PIPELINE_STATUS = {
  idle: 'secondary', running: 'info', completed: 'success', failed: 'danger',
};

export const NDBI_LEGEND = [
  { color: '#c0392b', label: 'NDBI Δ ≥ 0.30' },
  { color: '#e67e22', label: '≥ 0.20' },
  { color: '#f1c40f', label: '≥ 0.10' },
  { color: '#f9e79f', label: '< 0.10' },
];

export function ndbiColor(delta) {
  if (delta >= 0.3) return '#c0392b';
  if (delta >= 0.2) return '#e67e22';
  if (delta >= 0.1) return '#f1c40f';
  if (delta > 0) return '#f9e79f';
  return '#ecf0f1';
}

/** 0–1 → green / amber / red. */
export const signalColor = (v) => (v >= 0.7 ? '#198754' : v >= 0.4 ? '#ffc107' : '#dc3545');
/** 0–100 match score → colour. */
export const scoreColor = (s) => (s >= 85 ? '#198754' : s >= 60 ? '#ffc107' : s >= 40 ? '#fd7e14' : '#dc3545');
